metrics:
  performance:         {weight: 0.16}
  accessibility:       {weight: 0.12}
  best-practices:      {weight: 0.08}
  seo:                 {weight: 0.05}
  pwa:                 {weight: 0.05}
  code_quality:        {weight: 0.12}
  build_time:          {weight: 0.12}
  bundle_size:         {weight: 0.12}
  package_dependencies: {weight: 0.06}
  lines_of_code:       {weight: 0.06}
  file_count:          {weight: 0.06} 