metrics:
  performance:         {weight: 0.15}
  accessibility:       {weight: 0.11}
  best-practices:      {weight: 0.08}
  seo:                 {weight: 0.05}
  pwa:                 {weight: 0.05}
  code_quality:        {weight: 0.11}
  build_time:          {weight: 0.11}
  bundle_size:         {weight: 0.11}
  security:            {weight: 0.10}
  package_dependencies: {weight: 0.05}
  lines_of_code:       {weight: 0.05}
  file_count:          {weight: 0.05} 