metrics:
  performance:     {weight: 0.18}
  accessibility:   {weight: 0.13}
  best-practices:  {weight: 0.09}
  seo:             {weight: 0.05}
  pwa:             {weight: 0.05}
  code_quality:    {weight: 0.13}
  build_time:      {weight: 0.13}
  bundle_size:     {weight: 0.13}
  lines_of_code:   {weight: 0.06}
  file_count:      {weight: 0.05} 